version: "3.9"

services:
  #new app (angular_app)
  angular_app:
    container_name: angular_app
    image: pee-angular_app:1.0.0
    build: ./angular/gestorDeClientes/
    ports:
      - 4200:4200
    depends_on:
      - java_app
  java_app:
    container_name: java_app
    image: pee-java_app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
     - DATABASE_URL=jdbc:mysql://java_db:3306/mysql
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=rootpassword
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mysql
